### ISSUE TITLE
All qualities are scanned as unknown

### ISSUE THREAD

**Issue by iernie** [linuxserver/docker-medusa#20]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

I don't know who's fault this issue is, but it may be with the docker container.
See issue https://github.com/pymedusa/Medusa/issues/5969

A fresh container with this image and I am unable to find quality for any of my files. Everything gets marked as 'Unknown'. As described in the issue above, `knowit` was not even installed in the container and I had to install it with pip, but that didn't help.

**Comment by thelamer** [comment]
@iernie we do not install knowit because of how the extension system works in Medusa, they load python from the `/app/medusa/ext/` directory on startup, this includes knowit. 
It looks like maintainers are recommending pulling knowit from head of master in the issue you have referenced so they are aware of the issue.

We should not be pulling in some python extension at head from a github repo and replacing the code in their project, this should be fixed upstream. 

I have commented in that issue and will be closing this one.
